### ISSUE TITLE
페이스북 (앱) 계정만들기

### ISSUE THREAD

**Issue by ehnuje** [nahbee10/jungchi#18]
앱 계정이 없으면 공유버튼이나 좋아요버튼을 쓸 수 없음
- [x] 적당한 URL 고르기
- [x] 페이스북 어플리케이션 등록
- [x] 좋아요 버튼 만들기
- [x] 공유하기 버튼 만들기

**Comment by yhoonkim** [comment]
- [ ] URL 생기고 나서 좋아요 버튼 테스트해보기
