### ISSUE TITLE
"다시하기" 버튼이 동작을 안함

### ISSUE THREAD

**Issue by ehnuje** [nahbee10/jungchi#19]
button 으로 바꾼다음에 동작을 안함. 원래의 코드에서 span을 추가한다던지 지금 button 에서 동작하는 링크로 바꿔주던지 해야할듯

**Comment by yhoonkim** [comment]
`link_to` 함수를 block 형태로 적어주면 될 것 같습니다.

``` ruby
<%= link_to(vote_results_path, class: "btn btn-default") do %>
  <span class="glyphicon glyphicon-repeat" aria-hidden="true"> </span> 다시하기
<% end %>
```

아래와 같이 수정하여 커밋하였으니 의도와 맞는 확인하시고 참고하시기 바랍니다.

 @ehnuje 소스 확인 후 이슈 closes 해주세요~!
